version: '3.4'


services:

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  app_database:
    image: postgres:latest
    container_name: app_db
    environment:
      - POSTGRES_USER=posgres_database_708a_user
      - POSTGRES_PASSWORD=xgjpQtW5m5jbITR9NPDwFmqXQXgk7G7T
      - POSTGRES_DB=posgres_database_708a
    ports:
      - 5432:5433

    restart: always


  taskmanager.api:
    image: ${DOCKER_REGISTRY-}taskmanagerapi
    build:
      context: .
      dockerfile: TaskManagerApi/Dockerfile
 
    depends_on:
        - "app_database"
    environment: 
         - ConnectionStrings:DefaultConnection="Host=dpg-clga11njc5ks73edbiag-a.oregon-postgres.render.com;Database=posgres_database_708a;Username=posgres_database_708a_user;Password=xgjpQtW5m5jbITR9NPDwFmqXQXgk7G7T;Port=5432;"
         - ASPNETCORE_URLS=http://+80;


