version: '3.4'


services:

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  app_database:
    image: postgres:latest
    container_name: app_db
    environment:
      - POSTGRES_USER=applicationdb_ene4_user
      - POSTGRES_PASSWORD=ZIc9NSmAWAAMBft8YuScd3d2bnY6daoD
      - POSTGRES_DB=applicationdb_ene4
    ports:
      - 5432:5433

    restart: always


  taskmanager.api:
    image: ${DOCKER_REGISTRY-}taskmanagerapi
    build:
      context: .
      dockerfile: TaskManagerApi/Dockerfile
 
    depends_on:
        - "app_database"
    environment: 
         - ConnectionStrings:DefaultConnection="Host=dpg-cnsspkfjbltc73d5cic0-a.oregon-postgres.render.com;Database=applicationdb_ene4;Username=applicationdb_ene4_user;Password=ZIc9NSmAWAAMBft8YuScd3d2bnY6daoD;Port=5432;"
         - ASPNETCORE_URLS=http://+80;


