version: '3.4'


services:

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  app_database:
    image: postgres:latest
    container_name: app_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=#Alexissanchez31
      - POSTGRES_DB=TaskManagerDb
    ports:
      - 5432:5433

    restart: always


  taskmanager.api:
    image: ${DOCKER_REGISTRY-}taskmanagerapi
    build:
      context: .
      dockerfile: TaskManagerApi/Dockerfile
 
    depends_on:
        - "app_database"
    environment: 
         - ConnectionStrings:DefaultConnection="Server=app_database;Database=TaskManagerDb;Username=postgres;Password=#Alexissanchez31;Port=5432;"
         - ASPNETCORE_URLS=http://+80;


