services:
  - type: web
    name: aspnet-mssql-redis-dockerfile
    runtime: docker
    region: frankfurt
    plan: free
    healthCheckPath: /
    envVars:
      - key: REDIS_HOST
        fromService:
          type: redis
          name: redis-cache
          property: host
      - key: REDIS_PORT
        fromService:
          type: redis
          name: redis-cache
          property: port
      - key: MSSQL_SERVER
        value: sql_server2022
      - key: MSSQL_DATABASE
        value: TaskManagerDb
      - key: MSSQL_USER
        value: SA
      - key: MSSQL_PASSWORD
        value: "#Alexissanchez31"
      - key: MSSQL_CONNECTION_STRING
        value: Server=${MSSQL_SERVER};Database=${MSSQL_DATABASE};User Id=${MSSQL_USER};Password=${MSSQL_PASSWORD};Encrypt=false;TrustServerCertificate=True;MultipleActiveResultSets=true;MultiSubnetFailover=True

  # Redis instance
  - type: redis
    name: redis-cache
    region: frankfurt
    ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere
    plan: free

  # MSSQL Database
  - type: mssql
    name: mssql-database
    region: frankfurt
    plan: free
    envVars:
      - key: SA_PASSWORD
        value: "#Alexissanchez31"
      - key: ACCEPT_EULA
        value: Y
    databases:
      - name: TaskManagerDb
        collation: SQL_Latin1_General_CP1_CI_AS
