services:
  - name: aspnet-app
    runtime: aspnet-core
    build: .
    ports:
      - port: 80
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      REDIS_HOST: redis
      REDIS_PORT: 6379
      SQLSERVER_HOST: sqlserver
      SQLSERVER_PORT: 1433
      SQLSERVER_DATABASE: TaskManagerDb
      SQLSERVER_USERNAME: SA
      SQLSERVER_PASSWORD: #Alexissanchez31
    dependencies:
      - redis
      - sqlserver

  - name: redis
    runtime: redis
    image: redis:latest
    instance_count: 1
    ports:
      - port: 6379
      - port: 16379 (Redis Sentinel)

  - name: sqlserver
    runtime: mssql
    image: mcr.microsoft.com/mssql/server:latest
    instance_count: 1
    ports:
      - port: 1433
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: #Alexissanchez31
    volumes:
      - name: sqlserver-data
        mount_path: /var/opt/mssql/data
