name: Deploy

on:
  workflow_dispatch:
jobs:
  build: 
    uses: ./.github/workflows/render-build-app.yml
    
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    
    steps: 
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
           service-id: ${{ secrets.RENDER_SERVICE_ID }}
           api-key: ${{ secrets.RENDER_API_KEY }}
