name: CI/CD

on: 
  push:
    branches: 
      - master

jobs:
  build:
    name: Building image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        
      - name: DockerHub login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./TaskManagerApi/Dockerfile 
          push: true
          tags: jermaine31/taskmanager_api:latest
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps: 
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: srv-clhmc9mg1b2c73afqqn0 # Can be found as part of the Deploy Hook
          api-key: rnd_opHPVmdaY46FRfLnWlcghqzSpV8B
