name: My Deploy

on: 
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to production
        uses: render-com/deploy-to-render@v0.3.2
        with:
          service-id: ${{ https://api.render.com/deploy/srv-clhmc9mg1b2c73afqqn0?key=zntE_EE5KqQ }}
          api-key: ${{ rnd_opHPVmdaY46FRfLnWlcghqzSpV8B }}
